services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_database
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 190202
    ports:
      - '8080:80'
    networks:
      - webnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 190202
      MYSQL_ROOT_PASSWORD: 190202
    networks:
      - webnet

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8081:80'
      - '443:443'
    depends_on:
      - wordpress
      - db
    networks:
      - webnet

networks:
  webnet:
