name: Deploy WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t nguyenthihien190202/your-custom-wordpress:latest .
        # Replace `nguyenthihien190202/your-custom-wordpress` with your Docker Hub username/repo

      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: nguyenthihien190202
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Replace `nguyenthihien190202` with your Docker Hub username

      - run: docker push nguyenthihien190202/your-custom-wordpress:latest
        # Replace `nguyenthihien190202/your-custom-wordpress` with your Docker Hub username/repo

      - name: Deploy to production
        run: |
          docker-compose down
          docker-compose up -d
        # Ensure docker-compose.yml and necessary files are in the repository
